#!/usr/bin/env bash
#Script that parses information about domains wit dig and awk

if [ "$#" -eq 1 ]
then
	DOMAIN=$(echo "$1")
	for SU in www lb-01 web-01 web-02
	do
		ADRESS=$(echo "$SU.$DOMAIN")
		RECORD=$(dig $ADRESS | awk '/ANSWER SECTION:/{getline; print $4}')
		POINTS=$(dig $ADRESS | awk '/ANSWER SECTION:/{getline; print $5}')
		echo "The subdomain $SU is a $RECORD record and points to $POINTS"
	done
else
	ADRESS=$(echo "$2.$1")
	SU=$(echo "$2")
	RECORD=$(dig $ADRESS | awk '/ANSWER SECTION:/{getline; print $4}')
	POINTS=$(dig $ADRESS | awk '/ANSWER SECTION:/{getline; print $5}')
	echo "The subdomain $SU is a $RECORD record and points to $POINTS"


fi;
exit 1
