#!/usr/bin/env bash
#Script that install nginx web server

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "+server_name_;+a 'rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'" /etc/nginx/sites-available/default
udo service nginx restart
