#!/usr/bin/env bash
#Script that install nginx web server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee  /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;\n location = /custom_404.html {root /var/www/html;\n internal;' /etc/nginx/sites-available/default
sudo service nginx restart
