#!/usr/bin/env bash
#Script that install nginx web server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee  /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/server_name_;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/server_name_;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;' /etc/nginx/sites-available/default
sudo service nginx restart
