#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
# and echo only some parameters
file="/etc/passwd"

while IFS=: read -r line
do
echo "$line" | cut -d":" -f1,3,6
done < $file
