#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
# and echo only some parameters
file="/etc/passwd"

while IFS=: read -r usr pwd id gid gecos home shell
do
echo "the user $usr is part of the $gid gang, lives in $home and rides $shell. $id's place is protected by the passcode $pwd, more info about the user here: $gecos"
done < $file
