#!/usr/bin/env bash
# script that checks if a file exists
# and checks some of its properties
file="school"

if [[ ! -e "$file" ]]
then
	echo "$file file does not exist"
else
	echo "$file file exists"
	if [[ -s $1 ]]
	then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi
	if [[  -f $file ]]
	then
		echo "$file is a regular file"
	fi
fi
